### ISSUE TITLE
工具箱在win7环境下无法运行

### ISSUE THREAD

**Issue by Tanghaolin0508** [ZiHaoSaMa66/OsEasy-ToolBox#11]
作者您好！请问为什么我学校的学生机（Windows7系统）运行您的噢易工具箱的软件的时候打不开，而且出现了这个提示。
![捕获](https://github.com/ZiHaoSaMa66/OsEasy-ToolBox/assets/153969173/66117041-8d7a-4cbb-be78-f369f2aba5be)

**Comment by ZiHaoSaMa66** [comment]
win7打不开因为Pyinstaller打包的特性
在哪个系统环境编译就只能在哪个系统使用
晚点会补充win7的程序包
（大概明天就可以了）

**Comment by ZiHaoSaMa66** [comment]
哥们尽力了 通宵把方法都试了一轮 

> 坑也踩的差不多了（😢

win7**不支持**目前工具箱使用的图形化框架

![CUT_20240106061152](https://github.com/ZiHaoSaMa66/OsEasy-ToolBox/assets/134737096/3eccd044-7fa3-44d5-bb76-90e20c2ce8e3)

**Comment by Tanghaolin0508** [comment]
作者您好！请问为什么我在Windows7 64位旗舰版运行您的软件的时候会出现这个报错提示？






                       
原始邮件
                       
                     

发件人："ZiHaoSaMa66"< ***@***.*** &gt;;

发件时间：2024/1/6 6:25

收件人："ZiHaoSaMa66/OsEasy-ToolBox"< ***@***.*** &gt;;

抄送人："Tanghaolin0508"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [ZiHaoSaMa66/OsEasy-ToolBox] 给本软件提的建议 (Issue #11)




 
哥们尽力了 通宵把方法都试了一轮
  
坑也踩的差不多了（😢
  
win7不支持目前工具箱使用的图形化框架
 
CUT_20240106061152.png (view on web)

**Comment by ZiHaoSaMa66** [comment]
因为win7不支持目前工具箱使用的图形化框架
以后有空可能会为win7重写Ui

**Comment by Tanghaolin0508** [comment]
好的，非常感谢您辛苦地研究这个软件，我会一直支持您！另外提一个建议：我通过查看您GitHub上的工具箱软件截图图片发现您研究的噢易工具箱软件暂时还没有解除教师机禁用学生机U盘的这个功能，也希望您日后能增加解除教师机禁用学生机U盘的这个功能。






                       
原始邮件
                       
                     

发件人："ZiHaoSaMa66"< ***@***.*** &gt;;

发件时间：2024/1/6 14:57

收件人："ZiHaoSaMa66/OsEasy-ToolBox"< ***@***.*** &gt;;

抄送人："Tanghaolin0508"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [ZiHaoSaMa66/OsEasy-ToolBox] 工具箱在win7环境下无法运行 (Issue #11)




 
因为win7不支持目前工具箱使用的图形化框架
 以后有空可能会为win7重写Ui

**Comment by ZiHaoSaMa66** [comment]
https://github.com/ZiHaoSaMa66/OsEasy-ToolBox-Lite/
兼容win7的版本完工咯

**Comment by Tanghaolin0508** [comment]
好的，非常感谢您的辛苦研发，希望软件以后能增加拦截教师机禁用学生机的U盘功能。






                       
原始邮件
                       
                     

发件人："ZiHaoSaMa66"< ***@***.*** &gt;;

发件时间：2024/1/27 6:13

收件人："ZiHaoSaMa66/OsEasy-ToolBox"< ***@***.*** &gt;;

抄送人："Tanghaolin0508"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [ZiHaoSaMa66/OsEasy-ToolBox] 工具箱在win7环境下无法运行 (Issue #11)




 
https://github.com/ZiHaoSaMa66/OsEasy-ToolBox-Lite/
 兼容win7的版本完工咯
