### ISSUE TITLE
关于工具软件的建议

### ISSUE THREAD

**Issue by Tanghaolin0508** [ZiHaoSaMa66/OsEasy-ToolBox#26]
作者您好！请问轻量版工具箱软件什么时候能恢复更新呢？我非常期待您更新轻量版工具箱软件。

**Comment by Tanghaolin0508** [comment]
另外请问能否在工具箱软件中增加一个可以拦截教师机控屏的数据包的功能

**Comment by ZiHaoSaMa66** [comment]
轻量版暂时不考虑更新
目前已有功能已经能实现基础脱控
暂时不考虑编写此功能（懒了w
有意向可以自行PR
