### ISSUE TITLE
添加新学生端程序名

### ISSUE THREAD

**Issue by ZiHaoSaMa66** [ZiHaoSaMa66/OsEasy-ToolBox#30]
反馈者未提供学生端版本
目测是v10.9以上
学生端新程序名: `MmcStudent.exe`

**Comment by SheepYhangCN** [comment]
我们这里用的是MmcStudent.exe 版本是10.9.1
附上程序目录供参考：https://www.123865.com/s/KPMSVv-9eCjv

**Comment by ZiHaoSaMa66** [comment]
🆗🆗

**Comment by ZiHaoSaMa66** [comment]
已更新 [1.7 Beta3 Release](https://github.com/ZiHaoSaMa66/OsEasy-ToolBox/releases/tag/v1.7_Beta3)
如有Bug请反馈qwq
