### ISSUE TITLE
广播命令格式是否能自动生成

### ISSUE THREAD

**Issue by SheepYhangCN** [ZiHaoSaMa66/OsEasy-ToolBox#32]
大部分机房都不会去修改端口
广播命令格式中实际有变化的只有本机IP和教师机IP
本机IP可以在ipconfig中查询 而教师机IP可以在噢易的设置选项中看到
或许可以把目前拦截的方式作为备用方案
而主方案直接使用```{#decoderName#:#h264#,#fullscreen#:0,#local#:#学生机#,#port#:7778,#remote#:#教师机#,#teacher_ip#:0,#verityPort#:7788}```
直接获取两个IP替换到这个命令里
省掉拦截的步骤
（主要是我这边机房不知道为什么经常拦截不到 还是直接替换IP管用（））

**Comment by ZiHaoSaMa66** [comment]
好
