### ISSUE TITLE
无法获取学生端路径 显示路径不存在 实际学生端程序正常运行

### ISSUE THREAD

**Issue by KevinllBin** [ZiHaoSaMa66/OsEasy-ToolBox#35]
![图片](https://github.com/user-attachments/assets/15a9e5d1-55fc-4eca-b9d7-71b4c6624342)
如上图 本校学生端运行名称为MmcStudent 以及MultiClient
![图片](https://github.com/user-attachments/assets/4dcd1094-e4cf-49f1-9218-8830bbcae3f6)

![图片](https://github.com/user-attachments/assets/f4ef134f-5e85-4547-ace5-4a721a5634eb)
希望能做出修改

**Comment by ZiHaoSaMa66** [comment]
请尝试使用`v1.7 Beta3`版本噢
这个问题在这个版本才得到修复 #30 
[releases link](https://github.com/ZiHaoSaMa66/OsEasy-ToolBox/releases/tag/v1.7_Beta3)
