### ISSUE TITLE
有些小bug，beta3.1

### ISSUE THREAD

**Issue by xiguagulu** [ZiHaoSaMa66/OsEasy-ToolBox#38]
替换完开学生端还是会被控制
作者能不能给一个联系方式

**Comment by xiguagulu** [comment]
> 替换完开学生端还是会被控制  挂起学生端学生端会闪退 作者能不能给一个联系方式

**Comment by ZiHaoSaMa66** [comment]
你好哥们 学生端会被控制可能是你没有执行
> `其他管理 -> 删除键盘锁驱动&控屏锁定程序&黑屏安静 -> 三者一起删除`
> 等待删除完毕后 可以按任意按键跳过注销脚本的等待
> 待注销完毕后回到登录回来继续步骤

如果执行了还是被控制可能是你的学生端版本太低&或者过高         
需要提供一下学生端目录文件

挂起学生端会闪退这个我不就不清楚了

**Comment by ZiHaoSaMa66** [comment]
恕我拒绝
