### ISSUE TITLE
能不能把窗口模式改成可以缩放的窗口啊？

### ISSUE THREAD

**Issue by xiguagulu** [ZiHaoSaMa66/OsEasy-ToolBox#42]
辛苦哥们了，版本就是 SheepYhangCN 这个哥们提供的版本
不然上课调不了窗口真的会很难受

**Comment by ZiHaoSaMa66** [comment]
?可以缩放是指在窗口广播下 自由调整广播窗口大小么
如果是我这边的窗口是可以自由调整大小的

**Comment by xiguagulu** [comment]
> ?可以缩放是指在窗口广播下 自由调整广播窗口大小么 如果是我这边的窗口是可以自由调整大小的

我们不行诶，不知道是版本问题还是系统问题，我们是win10的系统

**Comment by ZiHaoSaMa66** [comment]
试着用强制自由调整窗口大小的工具看看

**Comment by xiguagulu** [comment]
> 试着用强制自由调整窗口大小的工具看看

我找了几个软件，好像不行诶，好像似乎他软件设定就不给窗口化的啊

**Comment by ZiHaoSaMa66** [comment]
那没辙了
